[PHP]
; For override php.ini configuration.
; See php.ini-development, php.ini-production or offical documentation fo detail.

upload_max_filesize = 2M
expose_php = 0

; cookieのセキュアな設定
; 参照：https://www.php.net/manual/ja/session.security.ini.php
session.use_cookies = 1
session.use_only_cookies = 1
session.cookie_lifetime = 0
session.cookie_httponly = 1
session.use_strict_mode = 1
session.cookie_secure = 1 ; HSTSも検討するように。
session.cookie_samesite = "Strict"
session.gc_maxlifetime = 1440
;       session.gc_maxlifetime to 1440 (1440 seconds = 24 minutes):
session.use_trans_sid = 0
; session.trans_sid_tags=[limited tags]
; session.trans_sid_hosts=[limited hosts]
; session.referer_check=[originating URL]
session.cache_limiter = nocache
session.hash_function = "sha256"
; session.save_path = "" ; defaultの/tmpは危険だが他のユーザーがいないのでよし
