

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ${APP_SOURCE_PATH:?error}:/var/www/html
    configs:
      - source: msmtprc
        target: /var/www/.msmtprc
      - source: php_fpm_d_camagru_conf
        target: /usr/local/etc/php-fpm.d/za-camagru.conf

configs:
  msmtprc:
    file: ${SERVICES_APP_LOCAL_DIR:-.}/configs/msmtprc/.msmtprc.dev
  php_fpm_d_camagru_conf:
    file: ${SERVICES_APP_LOCAL_DIR:-.}/configs/php-fpm.d/camagru-dev.conf
