
services:
  mariadb:
    environment:
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-password}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-password}
    volumes:
      - ${SERVICES_MARIADB_LOCAL_DIR:-.}/datadir:/var/lib/mysql
